"""Константы приложения reviews."""

TEXT_FIELD_LENGTH = 256
SLUG_FIELD_LENGTH = 50
SCORE_MIN_VALUE = 1
SCORE_MAX_VALUE = 10
NAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
ROLE_MAX_LENGTH = 64
USERNAME_REGEX_SIGNS = r'^[\w.@+-]+\Z'
